const FOOD_DATA = {
    milk: [
        { en: "Almond, Rice or Soy Beverage - Calcium-fortified", cn: "杏仁/米/豆奶（加钙）", serving: "1杯 | 250毫升", mg: 300 },
        { en: "Buttermilk", cn: "酪乳", serving: "1杯 | 250毫升", mg: 300 },
        { en: "Cheese - Blue, Brick, Cheddar, Edam, Gouda, Gruyere, Swiss", cn: "奶酪（蓝纹/切达/高达/瑞士等）", serving: "50克", mg: 245 },
        { en: "Cheese - Mozzarella", cn: "马苏里拉奶酪", serving: "50克", mg: 200 },
        { en: "Cheese - Vegan", cn: "素食奶酪", serving: "1片 | 21克", mg: 118 },
        { en: "Cottage Cheese", cn: "农家干酪", serving: "1杯 | 250毫升", mg: 150 },
        { en: "Greek Yogurt, Plain, 2%", cn: "希腊酸奶（原味2%）", serving: "半杯 | 100克", mg: 283 },
        { en: "Ice Cream Vanilla Soft Serve", cn: "香草冰淇淋（软）", serving: "1杯 | 250毫升", mg: 232 },
        { en: "Kefir", cn: "开菲尔酸奶", serving: "3/4杯 | 175毫升", mg: 187 },
        { en: "Milk evaporated", cn: "炼乳（淡奶）", serving: "半杯 | 125毫升", mg: 367 },
        { en: "Milk powder, dry", cn: "奶粉", serving: "1/3杯 | 75毫升", mg: 270 },
        { en: "Milk skim, 1%, 2%, whole or chocolate", cn: "牛奶（脱脂/全脂/巧克力味）", serving: "1杯 | 250毫升", mg: 300 },
        { en: "Paneer", cn: "印度奶酪", serving: "100克", mg: 103 },
        { en: "Parmesan Cheese, grated", cn: "帕玛森奶酪（碎）", serving: "1汤匙 | 15毫升", mg: 70 },
        { en: "Processed Cheese Slices thin", cn: "加工奶酪片", serving: "1片 | 115克", mg: 115 },
        { en: "Yogurt drinkable", cn: "酸奶饮品", serving: "4/5杯 | 200毫升", mg: 191 },
        { en: "Yogurt frozen - vanilla", cn: "冻酸奶（香草味）", serving: "1杯 | 250毫升", mg: 218 },
        { en: "Yogurt fruit flavoured", cn: "水果酸奶", serving: "3/4杯 | 175毫升", mg: 200 },
        { en: "Yogurt plain", cn: "原味酸奶", serving: "3/4杯 | 175毫升", mg: 332 },
    ],
    fruitVeg: [
        { en: "Amaranth, boiled", cn: "苋菜（煮熟）", serving: "半杯 | 125毫升", mg: 146 },
        { en: "Artichoke cooked", cn: "洋蓟（煮熟）", serving: "1个", mg: 54 },
        { en: "Asparagus, boiled", cn: "芦笋（煮熟）", serving: "1杯 | 250毫升", mg: 44 },
        { en: "Avocado", cn: "牛油果", serving: "半个", mg: 9 },
        { en: "Beet Greens cooked", cn: "甜菜叶（煮熟）", serving: "半杯 | 125毫升", mg: 82 },
        { en: "Blueberry", cn: "蓝莓", serving: "半杯 | 125毫升", mg: 5 },
        { en: "Blueberry, Wild", cn: "野生蓝莓", serving: "半杯 | 125毫升", mg: 10 },
        { en: "Bok choy, Pak-choi cooked", cn: "小白菜/青菜（煮熟）", serving: "半杯 | 125毫升", mg: 84 },
        { en: "Broccoli cooked", cn: "西兰花（煮熟）", serving: "半杯 | 125毫升", mg: 33 },
        { en: "Chinese Broccoli gai lan - cooked", cn: "芥兰（煮熟）", serving: "半杯 | 125毫升", mg: 46 },
        { en: "Collard Greens cooked", cn: "羽衣甘蓝菜（煮熟）", serving: "半杯 | 125毫升", mg: 133 },
        { en: "Corn, sweet", cn: "甜玉米", serving: "半杯 | 125毫升", mg: 2 },
        { en: "Dandelion Greens cooked", cn: "蒲公英叶（煮熟）", serving: "半杯 | 125毫升", mg: 74 },
        { en: "Edamame, boiled", cn: "毛豆（煮熟）", serving: "1杯 | 250毫升", mg: 276 },
        { en: "Fennel bulb, raw", cn: "茴香球茎（生）", serving: "100克 | 半杯", mg: 49 },
        { en: "Figs dried", cn: "无花果干", serving: "10个", mg: 269 },
        { en: "Fireweed Leaves raw", cn: "柳兰叶（生）", serving: "半杯 | 125毫升", mg: 214 },
        { en: "Grapefruit", cn: "葡萄柚", serving: "半个", mg: 18 },
        { en: "Kale cooked", cn: "羽衣甘蓝（煮熟）", serving: "半杯 | 125毫升", mg: 49 },
        { en: "Kiwifruit", cn: "猕猴桃", serving: "1个", mg: 26 },
        { en: "Mustard Greens cooked", cn: "芥菜（煮熟）", serving: "半杯 | 125毫升", mg: 58 },
        { en: "Okra cooked", cn: "秋葵（煮熟）", serving: "半杯 | 125毫升", mg: 65 },
        { en: "Orange", cn: "橙子", serving: "1个（中等）", mg: 52 },
        { en: "Orange Juice - Calcium-fortified", cn: "橙汁（加钙）", serving: "1杯 | 250毫升", mg: 300 },
        { en: "Prunes, dried", cn: "西梅干", serving: "100克", mg: 43 },
        { en: "Rutabaga yellow turnip - cooked", cn: "芜菁甘蓝（煮熟）", serving: "半杯 | 125毫升", mg: 43 },
        { en: "Saskatoon Berry", cn: "萨斯卡通莓", serving: "100克", mg: 42 },
        { en: "Seaweed, dried agar", cn: "干琼脂/海藻", serving: "半杯 | 125毫升", mg: 50 },
        { en: "Snap Beans, fresh or frozen, cooked", cn: "四季豆（煮熟）", serving: "半杯 | 125毫升", mg: 31 },
        { en: "Snow Peas cooked", cn: "荷兰豆（煮熟）", serving: "半杯 | 125毫升", mg: 36 },
        { en: "Squash acorn, butternut", cn: "南瓜（橡子/奶油南瓜）", serving: "半杯 | 125毫升", mg: 35 },
        { en: "Turnip Greens cooked", cn: "萝卜缨（煮熟）", serving: "半杯 | 125毫升", mg: 104 },
    ],
    grains: [
        { en: "Bannock", cn: "班诺克面包", serving: "1块 | 42.6克", mg: 58 },
        { en: "Bread white", cn: "白面包", serving: "2片", mg: 76 },
        { en: "Chia Seeds", cn: "奇亚籽", serving: "1汤匙 | 15毫升", mg: 56 },
        { en: "Instant Oatmeal - fortified", cn: "速溶燕麦片（强化）", serving: "1袋 | 32克", mg: 100 },
        { en: "Quinoa", cn: "藜麦", serving: "半杯 | 125毫升", mg: 16 },
        { en: "Soy Flour", cn: "豆粉", serving: "半杯 | 125毫升", mg: 88 },
        { en: "Wild Rice", cn: "野米", serving: "半杯 | 125毫升", mg: 3 },
    ],
    legumes: [
        { en: "Baked Beans, plain, canned", cn: "烘豆（罐装原味）", serving: "1杯 | 250毫升", mg: 89 },
        { en: "Baked Beans, with pork, canned", cn: "烘豆（罐装含猪肉）", serving: "1杯 | 250毫升", mg: 154 },
        { en: "Black Eye Peas, boiled", cn: "黑眼豆（煮熟）", serving: "半杯 | 125毫升", mg: 106 },
        { en: "Chickpeas", cn: "鹰嘴豆", serving: "1杯 | 250毫升", mg: 84 },
        { en: "Great northern Beans, soaked, drained, cooked", cn: "大北豆（煮熟）", serving: "1杯 | 250毫升", mg: 138 },
        { en: "Hummus", cn: "鹰嘴豆泥", serving: "半杯 | 125毫升", mg: 49 },
        { en: "Navy Beans, soaked, drained, cooked", cn: "海军豆（煮熟）", serving: "1杯 | 250毫升", mg: 126 },
        { en: "Pinto Beans, soaked, drained, cooked", cn: "花豆（煮熟）", serving: "1杯 | 250毫升", mg: 86 },
        { en: "Soybeans", cn: "黄豆", serving: "1杯 | 250毫升", mg: 93 },
        { en: "White Beans Canned", cn: "白豆（罐装）", serving: "1杯 | 250毫升", mg: 191 },
    ],
    protein: [
        { en: "Almonds", cn: "杏仁", serving: "半杯 | 125毫升", mg: 200 },
        { en: "Caribou, cooked", cn: "驯鹿肉（煮熟）", serving: "75克", mg: 12 },
        { en: "Dessert Tofu", cn: "甜品豆腐", serving: "半杯 | 125毫升", mg: 130 },
        { en: "Duck, roasted", cn: "烤鸭", serving: "100克", mg: 15 },
        { en: "Elk, Roasted", cn: "麋鹿肉（烤）", serving: "75克", mg: 4 },
        { en: "Goose, Canada boiled", cn: "加拿大鹅肉（煮）", serving: "100克", mg: 25 },
        { en: "Grouse, cooked", cn: "松鸡肉（煮熟）", serving: "75克", mg: 10 },
        { en: "Meatless Bacon", cn: "素培根", serving: "1片", mg: 3 },
        { en: "Moose, Roasted", cn: "驼鹿肉（烤）", serving: "75克", mg: 5 },
        { en: "Nuts, Hickory", cn: "山核桃", serving: "51克", mg: 31 },
        { en: "Perch", cn: "鲈鱼", serving: "75克", mg: 76 },
        { en: "Salmon canned with bones", cn: "三文鱼罐头（带骨）", serving: "半罐 | 105克", mg: 240 },
        { en: "Sardines canned with bones", cn: "沙丁鱼罐头（带骨）", serving: "半罐 | 55克", mg: 200 },
        { en: "Smelt, Baked or Broiled", cn: "胡瓜鱼（烤）", serving: "75克", mg: 58 },
        { en: "Tofu regular with calcium Sulfate", cn: "豆腐（含硫酸钙）", serving: "84克", mg: 130 },
        { en: "Trout, rainbow Baked or Broiled", cn: "虹鳟鱼（烤）", serving: "75克", mg: 64 },
        { en: "Venison, roasted", cn: "鹿肉（烤）", serving: "75克", mg: 5 },
        { en: "Wall Eye", cn: "梭鲈鱼", serving: "75克", mg: 106 },
    ],
    other: [
        { en: "Basil, dried", cn: "干罗勒", serving: "1茶匙 | 5毫升", mg: 32 },
        { en: "Butter Chicken", cn: "黄油鸡", serving: "1杯 | 250毫升", mg: 121 },
        { en: "Chili con carne with beans canned", cn: "辣椒肉酱豆（罐装）", serving: "1杯 | 250毫升", mg: 84 },
        { en: "Cinnamon", cn: "肉桂", serving: "1茶匙 | 5毫升", mg: 24 },
        { en: "Cumin", cn: "孜然", serving: "1茶匙 | 5毫升", mg: 20 },
        { en: "Hemp Seeds", cn: "大麻籽", serving: "2汤匙 | 30毫升", mg: 15 },
        { en: "Molasses", cn: "糖蜜", serving: "1汤匙 | 15毫升", mg: 180 },
        { en: "Oregano, dried", cn: "干牛至", serving: "1茶匙 | 5毫升", mg: 24 },
        { en: "Tahini", cn: "芝麻酱", serving: "1汤匙 | 15毫升", mg: 65 },
        { en: "Tempeh, cooked", cn: "天贝（煮熟）", serving: "150克", mg: 144 },
    ]
};
